baseURL = "https://providers.xmpp.net/"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
title = "XMPP Providers"
canonifyurls = true
disableHugoGeneratorInject = true
Paginate = 10

defaultContentLanguage = "en"
languageCode = "en-us"
theme = "xmpp-providers"
enableEmoji = true

[author]
name = "XMPP Providers Team"

[Params]
subtitle = "Subtitle"
hideAuthor = false
dateFormat = "January 2, 2006"
